title: FZ Studio
description: Watercolour originals, art prints & greeting cards
url: https://leondecoding.github.io
baseurl: ""
markdown: kramdown
permalink: pretty

collections:
  artprints:
    output: true
    permalink: /art-prints/:name/
  originals:
    output: true
    permalink: /original-art/:name/
  cards:
    output: true
    permalink: /greeting-cards/:name/

defaults:
  - scope: { path: "", type: "posts" }
    values: { layout: post }
  - scope: { path: "", type: "artprints" }
    values: { layout: product, category: "Art Print" }
  - scope: { path: "", type: "originals" }
    values: { layout: product, category: "Original" }
  - scope: { path: "", type: "cards" }
    values: { layout: product, category: "Greeting Card" }
title: FZ Studio
logo: /assets/images/logo.svg   # 或 .png
title: FZ Studio
logo: /assets/images/logo-fzs.svg     # 你的 FZS 图标路径
default_currency: GBP                 # 用于列表页符号（£/$/€）
paypal_business_id: ""                # 若要启用表单，请填你的 PayPal 商业账号（email 或商户ID）
