const state={lang:localStorage.getItem("lang")||"en",socials:{youtube:"https://www.youtube.com/",instagram:"https://www.instagram.com/"},data:{},currentRoute:location.hash||"#/home"};
async function loadJSON(p){const r=await fetch(p);return r.json();}
function $(s,root=document){return root.querySelector(s);}
function h(t,a={},...c){const e=document.createElement(t);for(const[k,v]of Object.entries(a||{}))if(k==="style"&&typeof v==="object"){Object.assign(e.style,v)}else if(k.startsWith("on")&&typeof v==="function"){e.addEventListener(k.slice(2),v)}else if(v!==false&&v!=null){e.setAttribute(k,v===true?"":v)};for(const x of c.flat()){e.appendChild(typeof x==="string"?document.createTextNode(x):x);}return e;}
const routes={"#/home":renderHome,"#/our-story":renderStory,"#/blog":renderBlog,"#/original-art":()=>renderGallery(),"#/art-prints":()=>renderShop("prints"),"#/greeting-cards":()=>renderShop("cards"),"#/contact":renderContact,"#/login":renderLogin};
window.addEventListener("hashchange",()=>{state.currentRoute=location.hash||"#/home";renderRoute();});
function renderRoute(){(routes[state.currentRoute]||renderHome)();}
async function boot(){state.translations=await loadJSON("data/translations.json");state.data.original_art=await loadJSON("data/original_art.json");state.data.prints=await loadJSON("data/prints.json");state.data.cards=await loadJSON("data/cards.json");$("#ytLink").href=state.socials.youtube;$("#igLink").href=state.socials.instagram;renderNav();renderRoute();}
function renderNav(){const t=state.translations[state.lang].nav;const n=$("#nav");n.innerHTML="";const links=[["#/home",t.home],["#/our-story",t.ourStory],["#/blog",t.blog],["#/original-art",t.originalArt],["#/art-prints",t.artPrint],["#/greeting-cards",t.greetingCard],["#/contact",t.contact],["#/login",t.login||"Login"]];for(const [href,label] of links){n.append(h("a",{href, class: location.hash===href?"active":""}, label))}}
async function renderHome(){const v=$("#view");v.innerHTML="";v.append(h("section",{},h("div",{class:"hero"},h("img",{src:"assets/ph-10.svg",alt:"Hero"}))))}
async function renderStory(){const v=$("#view");v.innerHTML="";v.append(h("section",{},h("div",{class:"story-card"},h("p",{},"Hi, we are FZ Studio, an architectural designer and an artist, currently based in London, UK. We enjoy creating art by meditating and experimenting through drawing, painting, photographing and crafting. We love nature and wildlife. In our spare time, hiking and diving always refresh our mind for creativity."),h("p",{},"We also post arts and stories related to nature and life via our ",h("a",{href:state.socials.youtube,target:"_blank",rel:"noopener"},"Youtube")," and ",h("a",{href:state.socials.instagram,target:"_blank",rel:"noopener"},"Instagram"),"."),h("p",{},"Currently, we are introducing our first collection of watercolor greeting cards and art prints. We believe watercolor captures the atmosphere of nature and the unpredictable feature of watercolour makes it suitable for intuitive creation."))));v.append(h("section",{},h("div",{class:"newsletter"},h("h2",{},"NEW RELEASES & MORE"),h("p",{},"Sign up with your email address to receive updates for our new art releases, ideas from our craft and much more."),h("form",{class:"nl-form",onsubmit:(e)=>{e.preventDefault();alert('Thanks! We\\'ll be in touch.');}},h("input",{type:"text",name:"first",placeholder:"First Name",required:true}),h("input",{type:"text",name:"last",placeholder:"Last Name",required:true}),h("input",{type:"email",name:"email",placeholder:"Email Address",required:true}),h("button",{type:"submit"},"Sign Up")),h("small",{},"100% spam free. Unsubscribe at any time. We respect your privacy."))));}
async function renderBlog(){const v=$("#view");v.innerHTML="";const wrap=h("section",{},h("h1",{},"Blog"));const grid=h("div",{class:"gallery"});const posts=[];(posts.length?posts:new Array(3).fill(0)).forEach((_,i)=>{const it={image:`assets/ph-${i+11}.svg`};grid.append(h("div",{class:"card"},h("div",{class:"img"},h("img",{src:it.image,alt:"Blog"})),h("div",{class:"caption"},"Post"))));wrap.append(grid);v.append(wrap)}
async function renderGallery(){const v=$("#view");v.innerHTML="";const wrap=h("section",{});const grid=h("div",{class:"gallery"});state.data.original_art.forEach((it,i)=>{grid.append(h("div",{class:"card",onclick:()=>openLightbox(state.data.original_art,i)},h("div",{class:"img"},h("img",{src:it.image,alt:it.title_en})),h("div",{class:"caption"}, it.title_en))));});wrap.append(grid);v.append(wrap)}
function openLightbox(items,index){const lb=h("div",{class:"lightbox"}),inner=h("div",{class:"lb-inner"}),imgWrap=h("div",{class:"lb-img"}),cap=h("div",{class:"lb-caption"});const close=h("button",{class:"lb-close",onclick:()=>lb.remove()},"×");const prev=h("button",{class:"lb-prev",onclick:()=>{index=(index-1+items.length)%items.length;update();}},"‹");const next=h("button",{class:"lb-next",onclick:()=>{index=(index+1)%items.length;update();}},"›");function update(){const it=items[index];imgWrap.innerHTML="";imgWrap.append(h("img",{src:it.image,alt:it.title_en}));cap.textContent=it.title_en;}update();inner.append(imgWrap,cap,prev,next);lb.append(inner);document.body.append(lb);}
async function renderShop(kind){const v=$("#view");v.innerHTML="";const items=kind==="prints"?state.data.prints:state.data.cards;const wrap=h("section",{});const grid=h("div",{class:"gallery"});items.forEach((it,i)=>{grid.append(h("div",{class:"card",onclick:()=>openProduct(kind,items,i)},h("div",{class:"img"},h("img",{src:it.image,alt:it.title_en})),h("div",{class:"caption"}, it.title_en))));});wrap.append(grid);v.append(wrap)}
function openProduct(kind,items,index){const item=items[index];const modal=h("div",{class:"lightbox"}),inner=h("div",{class:"lb-inner"}),imgWrap=h("div",{class:"lb-img"}),content=h("div",{class:"product-panel"});const close=h("button",{class:"lb-close",onclick:()=>modal.remove()},"×");imgWrap.append(h("img",{src:item.image,alt:item.title_en}));const meta=h("div",{class:"meta"});meta.append(h("h3",{},item.title_en),h("p",{},item.description_en||"—"));const row1=h("div",{class:"row"});const sizeSelect=h("select",{},...((item.sizes||[]).map(s=>h("option",{value:s.price},s.label+" – $"+s.price))));row1.append(h("label",{},"Choose Size:"),sizeSelect);const row2=h("div",{class:"row"});const qty=h("input",{type:"number",min:"1",value:"1",style:{width:"80px"}});row2.append(h("label",{},"Qty:"),qty);const row3=h("div",{class:"row"});const price=h("strong",{},"$0");row3.append(h("span",{},"Price:"),price);const buy=h("div",{class:"row"});const btn=h("button",{class:"buy",onclick:()=>{const pp=item.paypal||"";if(pp)window.open(pp,"_blank");else alert("PayPal link not set.");}},"Buy via PayPal");buy.append(btn);meta.append(row1,row2,row3,buy);content.append(imgWrap,meta);inner.append(close,content);modal.append(inner);document.body.append(modal);function updatePrice(){const base=parseFloat(sizeSelect.value||"0");const q=parseInt(qty.value||"1",10)||1;price.textContent="$"+(base*q).toFixed(2);}sizeSelect.addEventListener("change",updatePrice);qty.addEventListener("input",updatePrice);updatePrice();}
function renderContact(){const v=$("#view");v.innerHTML="";v.append(h("section",{},h("h1",{},"Contact"),h("p",{style:{textAlign:"center"}},h("a",{href:"mailto:hello@example.com"},"Send Email"))))}
function renderLogin(){const v=$("#view");v.innerHTML="";v.append(h("section",{},h("h1",{},"Login / Sign up")))} boot();
