const state={lang:localStorage.getItem("lang")||"en",socials:{youtube:"https://youtube.com/",instagram:"https://instagram.com/"},data:{},currentRoute:location.hash||"#/home",sessionUser:JSON.parse(localStorage.getItem("sessionUser")||"null")};
async function loadJSON(p){const r=await fetch(p);return r.json();}function $(s,root=document){return root.querySelector(s);}function h(t,a={},...c){const e=document.createElement(t);for(const[k,v]of Object.entries(a||{})){if(k.startsWith("on")&&typeof v==="function")e.addEventListener(k.slice(2).toLowerCase(),v);else if(k==="html")e.innerHTML=v;else e.setAttribute(k,v);}for(const x of c){if(x==null)continue;e.append(typeof x==="string"?document.createTextNode(x):x);}return e;}
function setLang(lang){state.lang=lang;localStorage.setItem("lang",lang);renderNav();renderRoute();}
const routes={"#/home":renderHome,"#/our-story":renderStory,"#/blog":renderBlog,"#/original-art":()=>renderGallery("original_art"),"#/art-print":()=>renderShop("prints"),"#/greeting-card":()=>renderShop("cards"),"#/contact":renderContact,"#/login":renderLogin};
window.addEventListener("hashchange",()=>{state.currentRoute=location.hash||"#/home";renderRoute();});function renderRoute(){(routes[state.currentRoute]||renderHome)();}
function renderNav(){const nav=$("#nav");nav.innerHTML="";[["#/home","Home"],["#/our-story","Our Story"],["#/blog","Blog"],["#/original-art","Original Art"],["#/art-print","Art Print"],["#/greeting-card","Greeting Card"],["#/contact","Contact"]].forEach(([href,label])=>nav.append(h("a",{href,class:location.hash===href?"active":""},label)));nav.append(h("button",{onclick:()=> setLang(state.lang==="en"?"zh":"en")},"中文"));nav.append(h("a",{href:"#/login",class:location.hash==="#/login"?"active":""},"Login"));}
async function renderHome(){const v=$("#view");v.innerHTML="";v.append(h("section",{},h("div",{class:"hero"},h("img",{src:"assets/ph-10.svg",alt:"Hero"}))))}
async function renderStory(){const v=$("#view");v.innerHTML="";v.append(h("section",{},h("h1",{},"Our Story"),h("p",{},"Replace with your story text..."),h("div",{style:"margin-top:24px;text-align:center"},h("input",{type:"email",placeholder:"Your email",style:"padding:10px 12px;border:1px solid var(--border);border-radius:6px;"}),h("button",{style:"margin-left:8px",onclick:()=>alert('Subscribed!')},"Subscribe"))))}
async function renderBlog(){const v=$("#view");v.innerHTML="";const wrap=h("section",{}),grid=h("div",{class:"gallery"});(state.data.blog||[]).forEach(p=>grid.append(h("figure",{class:"thumb"},h("img",{src:p.cover,alt:""}),h("figcaption",{class:"caption"},"Post"))));wrap.append(grid);v.append(wrap)}
async function renderGallery(){const v=$("#view");v.innerHTML="";const wrap=h("section",{},h("h1",{},"Original Art")),grid=h("div",{class:"gallery"});(state.data.original_art||[]).forEach((it,idx)=>grid.append(h("figure",{class:"thumb"},h("img",{src:it.image,alt:""}),h("figcaption",{class:"caption"},it.title_en))));wrap.append(grid);v.append(wrap)}
async function renderShop(kind){const v=$("#view");v.innerHTML="";const items=state.data[kind]||[];const wrap=h("section",{},h("h1",{},kind==="prints"?"Art Print":"Greeting Card")),grid=h("div",{class:"gallery"});items.forEach(it=>grid.append(h("figure",{class:"thumb",onclick:()=>openProduct(it,items)},h("img",{src:it.image,alt:""}),h("figcaption",{class:"caption"},it.title_en))));wrap.append(grid);v.append(wrap)}
function openProduct(item,items){const modal=h("div",{class:"lightbox",onclick:(e)=>{if(e.target===modal)modal.remove();}}),inner=h("div",{class:"lb-inner",style:"max-width:min(96vw,1100px)"}),panel=h("div",{class:"product-panel"});panel.append(h("div",{class:"image"},h("img",{src:item.image,alt:""})),h("div",{class:"info"},h("h2",{},item.title_en),h("p",{style:"text-align:center"},""+(item.description_en||"")),h("div",{class:"row"},h("label",{},"Size:"),(function(){const s=h("select",{id:"sizeSel",onchange:()=>upd()});for(const x of item.sizes||[]) s.append(h("option",{value:x},x));return s;})()),h("div",{class:"row"},h("strong",{},"Price: "),h("span",{id:"pPrice"},"")),h("div",{class:"row"},h("strong",{},"Product Info: "),h("span",{id:"pInfo"},"")),h("div",{class:"row"},h("button",{class:"buy",onclick:()=>{const size=$("#sizeSel").value;const link=(item.paypalLinks||{})[size];if(!link){alert('Missing PayPal link');return;}window.open(link,'_blank','noopener');}},"Buy via PayPal"))));const close=h("button",{class:"lb-close",onclick:()=>modal.remove()},"✕");function upd(){const s=$("#sizeSel").value;const price=(item.prices||{})[s]||"";const p=$("#pPrice");if(p)p.textContent=price;const info=$("#pInfo");if(info)info.textContent=item.info_en||"";}inner.append(panel,close);document.body.append(modal);modal.append(inner);setTimeout(upd,0);}
function renderContact(){const v=$("#view");v.innerHTML="";v.append(h("section",{},h("h1",{},"Contact"),h("p",{style:"text-align:center"},"For commissions or questions, email us:"),h("p",{style:"text-align:center"},h("a",{href:"mailto:hello@example.com"},"Send Email"))))}
function renderLogin(){const v=$("#view");v.innerHTML="";v.append(h("section",{},h("h1",{},"Login / Sign up")))}(async function(){state.data.original_art=await loadJSON("data/original_art.json");state.data.prints=await loadJSON("data/prints.json");state.data.cards=await loadJSON("data/cards.json");state.data.blog=await loadJSON("data/blog.json");document.getElementById('ytLink').href=state.socials.youtube;document.getElementById('igLink').href=state.socials.instagram;renderNav();renderRoute();})();